### ISSUE TITLE
Partners toevoegen

### ISSUE THREAD

**Issue by DaanStapelbroek** [DaanStapelbroek/BuitengewoonBubbels#10]

**Comment by DaanStapelbroek** [comment]
per bedrijf:   logo en naam eronder ( fotos  max 100*100) 
bedrijven in grid formaat afh. van window breedte

Voorbeeld partner: http://www.alettefotografie.nl/

**Comment by PaulHabraken** [comment]
pagina http://www.buitengewoonbubbels.nl/partners/ is live. Je kunt partners  toevoegen in het menu. Links naar de pagina in footer moet ik nog aanpassen. Dat gaat nog niet lekker op alle paginas.
Alleen vanuit de hoofdpagina zijn de partners te bereiken

**Comment by PaulHabraken** [comment]
Alle social-links aangepast. Daan aub testen en issue sluiten wanneer accoord.

**Comment by DaanStapelbroek** [comment]
Links getest, werken allemaal inderdaad. Zal vanavond beginnen met het toevoegen van een aantal nieuwe partners. Op alle pagina's behalve de homepage is er wel een band ontstaan onder de footers?

**Comment by PaulHabraken** [comment]
Band is nu weg op pc browser.

Op tablets blijft er wel een band bestaan. Heeft allemaal te maken met de schuine balken op de site. Ik ga hier niet meer verder naar zoeken.

**Comment by DaanStapelbroek** [comment]
Okay, fijn dat hij op de PC iig weer zonder band is. Op tablets geen ramp, dan zullen we nog even verder kijken naar of we dat zelf later nog evt. kunnen aanpassen (zal ik voor onszelf een nieuw issue voor maken). Ik sluit 'm! (Y)
