### ISSUE TITLE
Mobile issue Buitengewoon Bubbels in schuine balk

### ISSUE THREAD

**Issue by DaanStapelbroek** [DaanStapelbroek/BuitengewoonBubbels#13]
Het woord Buitengewoon Bubbels in de schuine balk verkleinen zodat het volledig in beeld past.

**Comment by PaulHabraken** [comment]
Aangepast.  Op de chrome emulater ziet het er goed uit.Test even met een iPhone. en sluit issue.

**Comment by DaanStapelbroek** [comment]
Yep, ziet er heel mooi uit!
