### ISSUE TITLE
Achtergrond images niet zichtbaar op oude iPhones en iPads

### ISSUE THREAD

**Issue by PaulHabraken** [DaanStapelbroek/BuitengewoonBubbels#18]
Nieuwe achtergrond images zijn niet zichtbaar op oude iPhones/ iPads

**Comment by PaulHabraken** [comment]
Originele images teruggezet. Alles werkt weer.

@DaanStapelbroek 
Aub testen en issue sluiten

**Comment by DaanStapelbroek** [comment]
Werkt inderdaad!
