### ISSUE TITLE
Bel me terug button/veld op onze contactpagina

### ISSUE THREAD

**Issue by DaanStapelbroek** [DaanStapelbroek/BuitengewoonBubbels#19]
Indien mogelijk het plaatsen van een Bel Me Terug functie zoals op www.littlecupcakefactory.nl op de contactpagina. 

Wanneer dit mogelijk is dan zouden we ook de tekst moeten aanpassen op deze pagina.

**Comment by PaulHabraken** [comment]
Waar wil je dit plaatsen op de pagina? , een form is snel toegevoegd. 

Let er wel op dat het huidige contact form niet is beveiligd tegen "script kiddy's'. Het is dus mogelijk om heel veel berichten te sturen.

**Comment by DaanStapelbroek** [comment]
Als het kan onder het contactformulier dat nu op onze contactpagina staat. Vergelijkbaar als op www.littlecupcakefactory.nl/contact.html 

Dit zou dan de bijbehorende tekst zijn: 

Laat hieronder uw telefoonnummer achter en wij bellen u zo snel mogelijk terug!

Bel mij terug (op de button)
