### ISSUE TITLE
Weergave wanneer je Buitengewoon Bubbels googled

### ISSUE THREAD

**Issue by DaanStapelbroek** [DaanStapelbroek/BuitengewoonBubbels#3]
Als je buitengewoon bubbels googled zouden we het liefst: 

“Buitengewoon Bubbels | champagnebar met stijl” te zien krijgen. 

Nu is het Buitengewoon Bubbels: Home

**Comment by DaanStapelbroek** [comment]
Daan probeert het op te zoeken in de Google SEO

**Comment by DaanStapelbroek** [comment]
Gevonden in het Google document op pagina 4:

A title tag tells both users and search engines what the topic of
a particular page is. The <title> tag should be placed within the
<head> tag of the HTML document. Ideally, you should create a
unique title for each page on your site.

If your document appears in a search results page, the contents of
the title tag will usually appear in the first line of the results

Wat er dus achter <title> aan het begin van de code staat, zou op Google als zoekresultaat gegeven moeten worden. 

EDIT: Ik merk dat iedere keer als ik hier code intyp, Github deze niet weergeeft. Er staat bijvoorbeeld een aantal keer in deze tekst < title > (maar dan zonder de spaties)

**Comment by DaanStapelbroek** [comment]
Wanneer je ons nu Googeld krijg je:

Buitengewoon Bubbels | Mobiele champagnebar | Home

We komen dus in de buurt. Ik denk dat we in het bestandje header-home.php de regel

< title > Buitengewoon Bubbels | Mobiele champagnebar | <?php echo $post->post_title; ?> < /title >

moeten aanpassen naar

< title > Buitengewoon Bubbels | Mobiele champagnebar met stijl < /title >

(Maar dan alles zonder spaties)

Kan dat kloppen?

**Comment by PaulHabraken** [comment]
Wil, je dit alleen voor de home page ?  dan kun je inderdaad de titel statisch maken. (Dus onafhankelijk van de page title.

**Comment by DaanStapelbroek** [comment]
Ik denk het wel, alleen de Homepage wordt zo direct weergegeven op Google, voor de andere pagina's is het niet zo belangrijk.

**Comment by PaulHabraken** [comment]
Uitgevoerd.  Het duurt natuurlijk even voordat dit in google zoekresultaten zichtbaar is
